inherit_from: .rubocop_todo.yml

require: 
  - rubocop-jekyll
  - rubocop-performance
  - rubocop-rspec

inherit_gem:
  rubocop-jekyll: .rubocop.yml

AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - spec/**/*

RSpec/FilePath:
  Exclude:
    - spec/jekyll-relative-links/generator_excerpt_frontmatter_spec.rb
    - spec/jekyll-relative-links/context_spec.rb
    - spec/jekyll-relative-links/generator_spec.rb
